### ISSUE TITLE
ERROR: Caught exception in do_training(): probabilities contain NaN

### ISSUE THREAD

**Issue by robinwang08** [deepmedic/deepmedic#184]
Not sure how to debug this issue properly, but I am getting the following error. I followed the required data pre-processing although my dimensions may be a bit larger than 200x200x200 sometimes. All voxels are [1,1,1]. I am not using any ROI masks and I've kept many of the default values in the configuration files, except that I am using 4 input channels. Has anyone seen this error?

ERROR: Caught exception in do_training(): probabilities contain NaN
Traceback (most recent call last):
  File "/home/user1/xyz/deepmedic/routines/training.py", line 292, in do_training
    labelsForCentralOfSegmentsForSubepTrain) = parallelJobToGetDataForNextTraining.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/user1/xyz/deepmedic/dataManagement/sampling.py", line 107, in getSampledDataAndLabelsForSubepoch
    lbls_predicted_part_of_samples_from_job) = load_subj_and_get_samples( *( [job_i]+args_sampling_job ) )
  File "/home/user1/xyz/deepmedic/dataManagement/sampling.py", line 305, in load_subj_and_get_samples
    sampling_map)
  File "/home/user1/xyz/deepmedic/dataManagement/sampling.py", line 497, in sample_coords_of_segments
    p=flattenedConstrainedWithImageBoundariesMaskToSample)
  File "mtrand.pyx", line 793, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN

**Comment by robinwang08** [comment]
Looking at constrainedWithImageBoundariesMaskToSample in sample_coords_of_segments(), for example, I have a [312,312,115] image and inspecting the constrainedWithImageBoundariesMaskToSample variable shows a 312x115 array, but a large number of the cells are blank for some reasons. Related?
